### PR TITLE
feat: add 404 page

### PR DESCRIPTION
**Pull request by chmette**

### CODE REVIEW

**Comment by AdrianValdes** [comment]
Remember that if you make two PR at the same time you will have to some some conflicts once we merge. Because on can make changes in the PR so the other PR doesn't have the changes. We should make on PR at the time to avoid git problems and keep the flow easier to deal with.

**Comment by chmette** [comment]
but we can merge the style fix, pull main rebase the 404  and be fine right?

**Comment by chmette** [comment]
removed inline styles

**Review by AdrianValdes — APPROVED** [review]
Thanks for making the 404 page.

**Pull request merged**
